global:
  load_balancing:
    algorithm: weighted-rr
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  logging:
    level: info
    path: /var/log/balto/balto.log
  metrics:
    enabled: true
  cors:
    enabled: false
    allowed_origins: []
  timeouts:
    read: 5s
    write: 5s
    idle: 30s

server:
  port: ":5500"

services:
  - domain: localhost
    path_prefix: "*"
    ports: ["8080", "8081", "8082"]
